# Introduction to NumPy

- **NumPy** is a Python library.  
- **NumPy** is used for working with **arrays**.  
- **NumPy** is short for **"Numerical Python"**.  


In [24]:
#Create array
my_list =[1,2,3]
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [2]:
#Create Matrix using numpy
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#Numpy range
np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Numpy range with even numbers
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
#Generate a arrays of all zeros
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# Linespace which gives array within a range with a third argument as number of elements i.e., 10
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
#Identitiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#Generate random numbers from U(0,1)
np.random.rand(5)

array([0.1513475 , 0.28861588, 0.67546305, 0.5484586 , 0.97303547])

In [12]:
#Generate 2D random numbers from U(0,1)
np.random.rand(5,5)

array([[0.42861326, 0.69456585, 0.4642477 , 0.65373991, 0.0527409 ],
       [0.97212477, 0.08178378, 0.16725974, 0.52996123, 0.81835427],
       [0.88028974, 0.10262245, 0.19987647, 0.64244865, 0.5329495 ],
       [0.94821925, 0.97601892, 0.04021753, 0.24435151, 0.1675579 ],
       [0.53015075, 0.51085096, 0.57661759, 0.01836413, 0.74787054]])

In [13]:
#Generate random numbers from N(0,1)
np.random.randn(2)

array([-1.74168932, -0.62339892])

In [14]:
#Generate 2D random numbers from N(0,1)
np.random.randn(2,2)

array([[ 1.10613018, -0.16898   ],
       [ 2.71409673,  0.69411934]])

In [15]:
#Generate random number from a range
np.random.randint(1,100)

96

In [16]:
#Generate random numbers from a range
np.random.randint(1,100,10)

array([49,  9, 80, 48, 57, 16,  1, 80, 84, 46], dtype=int32)

In [17]:
#To reshape a array into another dimension
arr=np.arange(25)
arr
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr=np.random.randint(0,50,10)
ranarr



array([15, 36,  9, 49, 26, 26, 20,  6, 27, 14], dtype=int32)

In [19]:
#To det the max
ranarr.max()

np.int32(49)

In [20]:
#To get the min
ranarr.min()

np.int32(6)

In [21]:
#To get the index location
ranarr.argmax()

np.int64(3)

In [23]:
ranarr.argmin()

np.int64(7)