In [1]:
import numpy as np

In [2]:
arr=np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#To get the perticula value or index
arr[8]

np.int64(8)

In [5]:
#To get slice of array upto 5 index
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
#To get slice of array upto 6 index
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
#To get slice starting from 5 index
arr[5:]

array([5, 6, 7, 8, 9])

In [8]:
#Broadcast
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [13]:
arr=np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr=arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:]=99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
#2D matrix
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
#Extract particular value
arr_2d[0][0]

np.int64(5)

In [24]:
#Extract particular row
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[1][1]

np.int64(25)

In [30]:
#Extract particular value 
arr_2d[2,1]
#or
arr_2d[2][1]

np.int64(40)

In [32]:
#Extracts rows
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
#extracts subsections of matrix
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
#Conditional selection

In [36]:
arr=np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
bool_arr = arr > 5

In [40]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr < 3 ]

array([1, 2])