In [27]:
#Create array
my_list =[1,2,3]
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [29]:
#Create Matrix using numpy
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#Numpy range
np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#Numpy range with even numbers
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [30]:
#Generate a arrays of all zeros
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
# Linespace which gives array within a range with a third argument as number of elements i.e., 10
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [37]:
#Identitiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
#Generate random numbers from U(0,1)
np.random.rand(5)

array([0.47061983, 0.38987051, 0.83290016, 0.5508462 , 0.9172373 ])

In [41]:
#Generate 2D random numbers from U(0,1)
np.random.rand(5,5)

array([[0.86107611, 0.96326087, 0.67007989, 0.73309306, 0.42009429],
       [0.15812817, 0.062636  , 0.03226611, 0.04136153, 0.04794971],
       [0.63800643, 0.10604677, 0.71730837, 0.77452807, 0.97206786],
       [0.79721777, 0.79790048, 0.26721378, 0.33830533, 0.74529426],
       [0.09351758, 0.01722362, 0.1404316 , 0.18789758, 0.51263474]])

In [40]:
#Generate random numbers from N(0,1)
np.random.randn(2)

array([0.33937594, 1.67486611])

In [42]:
#Generate 2D random numbers from N(0,1)
np.random.randn(2,2)

array([[ 0.2327826 , -1.58823062],
       [-0.97160238, -0.09721375]])

In [46]:
#Generate random number from a range
np.random.randint(1,100)

52

In [45]:
#Generate random numbers from a range
np.random.randint(1,100,10)

array([39,  4, 94, 89, 91, 37, 78, 27, 24, 44], dtype=int32)

In [53]:
#To reshape a array into another dimension
arr=np.arange(25)
arr
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
ranarr=np.random.randint(0,50,10)
ranarr



array([31, 36,  4, 41, 19, 28, 17, 15, 18,  7], dtype=int32)

In [60]:
#To det the max
ranarr.max()

np.int32(41)

In [61]:
#To get the min
ranarr.min()

np.int32(4)

In [62]:
#To get the index location
ranarr.argmax()

np.int64(3)

In [63]:
ranarr.argmin()

np.int64(2)